kind: Service
apiVersion: v1
metadata:
  name: crdb-changefeed-publisher-metrics
  namespace: default
  labels:
    name: crdb-changefeed-publisher-metrics
spec:
  type: NodePort
  selector:
    app: crdb-changefeed-publisher
  ports:
    - targetPort: 8001
      protocol: TCP
      port: 8001
